server:
  port: 8080
spring:
  application:
    name: protea-project
#   datasource:
#     url: jdbc:mysql://localhost:3306/plamya?useSSL=false # или ссылка для любой другой реляционной базы данных
#     username: root # поменяйте если не совпадает с вашим
#     password: qwerdsa660 # это тоже
#   jpa:
#     open-in-view: false
#     hibernate:
#       ddl-auto: update
#     show-sql: true
#     properties:
#       hibernate:
#         enable_lazy_load_no_trans: true
#         format_sql: true
#   data:
#     redis:
#       host: localhost
#       port: 6379
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 247464265015-astrh9vll11l22scpds7rdn6q8b8bbo7.apps.googleusercontent.com
            client-secret: RZptmh1c6LEfNhYHDLqGLqAJ
          scope: email, profile
        # provider:
        #   github:
        #     user-name-attribute: login